# Generated by Django 3.1.4 on 2021-01-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_auto_20201226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='asset_id',
            field=models.UUIDField(),
        ),
    ]
