# Generated by Django 3.1.4 on 2020-12-26 19:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cryptocurrency',
            options={'verbose_name': 'Crypto Currency', 'verbose_name_plural': 'Crypto Currencies'},
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='name',
            field=models.CharField(help_text='The full name of the cryptocurrency', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='symbol',
            field=models.CharField(help_text='A 3 Letter (usually) identifier for the cryptocurrency, e.g. BTC or ETH', max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='fiatcurrency',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
