# Generated by Django 3.1.4 on 2021-01-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0002_auto_20201226_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricerecord',
            name='from_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='pricerecord',
            name='to_id',
            field=models.UUIDField(),
        ),
    ]
